import {
  Activity,
  BellRing,
  Blocks,
  BookUp,
  DatabaseZap,
  GitBranch,
  Mail,
  ScrollText,
  Terminal,
  AlertTriangle,
  BarChart3,
  Bell,
  BetweenHorizontalStart,
  Bookmark,
  Bug,
  Calendar,
  ChartLine,
  CheckSquare,
  Clock,
  Code,
  Database,
  FileCode,
  FilePlus,
  FileText,
  Filter,
  Flag,
  FolderTree,
  Gauge,
  Gem,
  Image,
  Info,
  Layers,
  Link,
  List,
  ListChecks,
  ListOrdered,
  ListTree,
  Lock,
  Map,
  MessageSquare,
  Paperclip,
  Puzzle,
  Quote,
  Rocket,
  Search,
  Shapes,
  Sparkles,
  SquareCheckBig,
  Star,
  Table,
  Tags,
  Target,
  Timer,
  TrendingUp,
  Users,
  Workflow,
  Zap,
  type LucideIcon,
} from "lucide-react";

/**
 * Lucide icons a SERVER-declared `icon` name may resolve to. A curated map, not
 * `lucide-react/dynamic`, which took the build from 127 chunks / 5.6 MB to
 * 1876 chunks / 13 MB. Unknown names render the neutral fallback. Shared with
 * ValueChip so issue types and extensions agree on a name.
 */
const ICONS: Record<string, LucideIcon> = {
  // Issue types (seeded by the backend).
  "square-check-big": SquareCheckBig,
  bug: Bug,
  bookmark: Bookmark,
  sparkles: Sparkles,
  gem: Gem,
  shapes: Shapes,
  // Page extensions (server/src/radd/modules/pages/extensions.py).
  "list-tree": ListTree,
  "folder-tree": FolderTree,
  info: Info,
  link: Link,
  "between-horizontal-start": BetweenHorizontalStart,
  tags: Tags,
  "file-plus": FilePlus,
  // Plugin navigation (RADD-1390): a manifest's NavItemSpec.icon names one of these, so a
  // plugin page never needs a host edit to show its icon.
  activity: Activity,
  "bell-ring": BellRing,
  blocks: Blocks,
  "book-up": BookUp,
  "database-zap": DatabaseZap,
  "git-branch": GitBranch,
  mail: Mail,
  "scroll-text": ScrollText,
  terminal: Terminal,
  // General purpose, for anything a plugin declares.
  "alert-triangle": AlertTriangle,
  "bar-chart-3": BarChart3,
  bell: Bell,
  calendar: Calendar,
  "chart-line": ChartLine,
  "check-square": CheckSquare,
  clock: Clock,
  code: Code,
  database: Database,
  "file-code": FileCode,
  "file-text": FileText,
  filter: Filter,
  flag: Flag,
  gauge: Gauge,
  image: Image,
  layers: Layers,
  list: List,
  "list-checks": ListChecks,
  "list-ordered": ListOrdered,
  lock: Lock,
  map: Map,
  "message-square": MessageSquare,
  paperclip: Paperclip,
  puzzle: Puzzle,
  quote: Quote,
  rocket: Rocket,
  search: Search,
  star: Star,
  table: Table,
  target: Target,
  timer: Timer,
  "trending-up": TrendingUp,
  users: Users,
  workflow: Workflow,
  zap: Zap,
};

/** What an unrecognised name renders as — visibly a placeholder, not a gap. */
const FALLBACK_ICON = Puzzle;

/** The component for a server-declared icon name, or undefined. */
export const iconFor = (name: string | null | undefined): LucideIcon | undefined =>
  name ? ICONS[name] : undefined;

/** The component for a name, falling back to the placeholder. */
export const iconOrFallback = (name: string | null | undefined): LucideIcon =>
  iconFor(name) ?? FALLBACK_ICON;
