{{- if .Values.migration.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}-migrate-{{ .Release.Revision }}
  labels:
    {{- include "radd.labels" . | nindent 4 }}
    app.kubernetes.io/component: migrate
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  backoffLimit: 2
  template:
    metadata:
      labels:
        {{- include "radd.labels" . | nindent 8 }}
        app.kubernetes.io/component: migrate
    spec:
      restartPolicy: Never
      {{- include "radd.imagePullSecrets" . | nindent 6 }}
      containers:
        - name: migrate
          image: {{ include "radd.image" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["alembic", "upgrade", "head"]
          workingDir: /app/server
          env:
            {{- include "radd.env" . | nindent 12 }}
          {{- include "radd.envFrom" . | nindent 10 }}
{{- end }}
