/** The SDK's runtime names, read from `packages/plugin-sdk/src/index.ts` (following `export *`, skipping
 *  types). A name missing from the shim is `undefined` in every remote — so it is never hand-kept. */
import { readFileSync, statSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { parse } from "@babel/parser";

const here = dirname(fileURLToPath(import.meta.url));
export const SDK_INDEX = resolve(here, "../packages/plugin-sdk/src/index.ts");
export const SDK_SHIM = resolve(here, "../public/shared/radd-plugin-sdk.js");

const IDENT = /^[A-Za-z_$][A-Za-z0-9_$]*$/;

function resolveModule(from, specifier) {
  const base = resolve(dirname(from), specifier);
  for (const candidate of [base, `${base}.ts`, `${base}.tsx`, resolve(base, "index.ts")]) {
    if (statSync(candidate, { throwIfNoEntry: false })?.isFile()) return candidate;
  }
  throw new Error(`sdk-exports: cannot resolve ${specifier} from ${from}`);
}

function declaredNames(declaration) {
  switch (declaration.type) {
    case "FunctionDeclaration":
    case "ClassDeclaration":
    case "TSEnumDeclaration":
      return [declaration.id.name];
    case "VariableDeclaration":
      return declaration.declarations.flatMap((d) => (d.id.type === "Identifier" ? [d.id.name] : []));
    default:
      return []; // type aliases, interfaces, `declare` blocks
  }
}

/** Every value name `file` exports, in source order, `export *` expanded in place. */
export function valueExports(file = SDK_INDEX, seen = new Set()) {
  if (seen.has(file)) return [];
  seen.add(file);
  const ast = parse(readFileSync(file, "utf8"), { sourceType: "module", plugins: ["typescript", "jsx"] });
  const names = [];
  for (const node of ast.program.body) {
    if (node.type === "ExportNamedDeclaration" && node.exportKind !== "type") {
      if (node.declaration) names.push(...declaredNames(node.declaration));
      for (const spec of node.specifiers ?? []) {
        if (spec.exportKind !== "type") names.push(spec.exported.name ?? spec.exported.value);
      }
    } else if (node.type === "ExportAllDeclaration" && node.exportKind !== "type") {
      names.push(...valueExports(resolveModule(file, node.source.value), seen));
    }
  }
  return [...new Set(names)];
}

/** A shim module re-exporting the host singleton `id` under `names`. */
export function shimSource(id, names, hasDefault) {
  const valid = names.filter((n) => n !== "default" && IDENT.test(n));
  const lines = [
    `// AUTO-GENERATED by scripts/gen-shared-shims.mjs — do not edit.`,
    `// Re-exports the host singleton for "${id}" from the shared federation scope.`,
    `const M = globalThis.__RADD_SHARED__ && globalThis.__RADD_SHARED__[${JSON.stringify(id)}];`,
    `if (!M) throw new Error("radd federation: shared module ${id} not registered by host");`,
    ...valid.map((n) => `export const ${n} = M[${JSON.stringify(n)}];`),
  ];
  if (hasDefault) lines.push(`export default M["default"] !== undefined ? M["default"] : M;`);
  return lines.join("\n") + "\n";
}

/** A shim for a LAZILY shared module (RADD-1397). The host registers a LOADER rather than the
 *  instance, because the module ships in a chunk the host loads on first use; the shim's top-level
 *  await calls it, so a remote importing the module gets the host's copy, on demand. */
export function lazyShimSource(id, names) {
  const valid = names.filter((n) => n !== "default" && IDENT.test(n));
  return [
    `// AUTO-GENERATED by scripts/gen-shared-shims.mjs — do not edit.`,
    `// Re-exports the host's "${id}", loaded with the host's editor engine rather than at boot.`,
    `const load = globalThis.__RADD_SHARED_LAZY__ && globalThis.__RADD_SHARED_LAZY__[${JSON.stringify(id)}];`,
    `if (!load) throw new Error("radd federation: shared module ${id} not registered by host");`,
    `const M = await load();`,
    ...valid.map((n) => `export const ${n} = M[${JSON.stringify(n)}];`),
  ].join("\n") + "\n";
}

/** What `public/shared/radd-plugin-sdk.js` must contain. */
export function sdkShimSource() {
  return shimSource("@radd/plugin-sdk", valueExports(), false);
}
