"""Build the milestone model at import time so it lands in `Base.metadata` for
Alembic + `import_models` (the model itself is generated by the kernel from the
declarative `SPEC` — no hand-written columns). Idempotent."""

from radd.sdk import entities

from .spec import SPEC

Milestone = entities.build_model(SPEC)
