// GENERATED by web/scripts/plugin-packages.mjs (RADD-1373) — do not edit.
// Core plugins' UI, bundled with the host and registered at boot. Optional plugins are
// remotes, loaded at runtime when enabled.
import type { PluginModule } from "@radd/plugin-sdk";
import audit from "@radd-plugin-ui/audit";
import auth from "@radd-plugin-ui/auth";
import automations from "@radd-plugin-ui/automations";
import backup from "@radd-plugin-ui/backup";
import cycles from "@radd-plugin-ui/cycles";
import fields from "@radd-plugin-ui/fields";
import forms from "@radd-plugin-ui/forms";
import groups from "@radd-plugin-ui/groups";
import items from "@radd-plugin-ui/items";
import itemtypes from "@radd-plugin-ui/itemtypes";
import labels from "@radd-plugin-ui/labels";
import projects from "@radd-plugin-ui/projects";
import releases from "@radd-plugin-ui/releases";
import teams from "@radd-plugin-ui/teams";
import timelogging from "@radd-plugin-ui/timelogging";
import vcs from "@radd-plugin-ui/vcs";
import workflow from "@radd-plugin-ui/workflow";

export const STATIC_PLUGINS: Record<string, PluginModule> = {
  "audit": audit,
  "auth": auth,
  "automations": automations,
  "backup": backup,
  "cycles": cycles,
  "fields": fields,
  "forms": forms,
  "groups": groups,
  "items": items,
  "itemtypes": itemtypes,
  "labels": labels,
  "projects": projects,
  "releases": releases,
  "teams": teams,
  "timelogging": timelogging,
  "vcs": vcs,
  "workflow": workflow,
};
