"""views saved boards lists

Revision ID: 0562875fb08a
Revises: cb29f8c473c0

Purely additive (spec 08): the saved-views table. Hand-written (not
autogenerated) so the parallel spec-06 branch's models can't leak in;
a sibling head on cb29f8c473c0 is expected — apply with `upgrade heads`.
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


revision = '0562875fb08a'
down_revision = 'cb29f8c473c0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.create_table('views',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('view_type', sa.String(length=20), nullable=False),
    sa.Column('filters', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('group_by', sa.String(length=20), nullable=True),
    sa.Column('owner_id', sa.Uuid(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('fk_views_owner_id_users')),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_views_project_id_projects')),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_views_workspace_id_workspaces')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_views'))
    )
    op.create_index(op.f('ix_views_owner_id'), 'views', ['owner_id'], unique=False)
    op.create_index(op.f('ix_views_project_id'), 'views', ['project_id'], unique=False)
    op.create_index(op.f('ix_views_workspace_id'), 'views', ['workspace_id'], unique=False)


def downgrade() -> None:
    op.drop_index(op.f('ix_views_workspace_id'), table_name='views')
    op.drop_index(op.f('ix_views_project_id'), table_name='views')
    op.drop_index(op.f('ix_views_owner_id'), table_name='views')
    op.drop_table('views')
