"""directory sync state (spec 85)

`directory_sync_state`: one row per periodic directory sync (kind PK
user_sync|group_sync) — when it last ran and its summary payload; served by
GET /ldap/sync-status.

Revision ID: 12e3da9fab36
Revises: 8dcb99d261e6

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '12e3da9fab36'
down_revision = '8dcb99d261e6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('directory_sync_state',
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('last_run_at', sa.DateTime(), nullable=False),
    sa.Column('last_result', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('kind', name=op.f('pk_directory_sync_state'))
    )
    # ### end Alembic commands ###
    # NOTE: autogenerate's ix_doc_pages_fts drop/create is a false positive
    # (functional GIN index alembic can't introspect) — stripped both ways.


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('directory_sync_state')
    # ### end Alembic commands ###
