"""screens field layout

Revision ID: 1ec5ca425fcd
Revises: bb706d3802ae

"""
from alembic import op
import sqlalchemy as sa


revision = '1ec5ca425fcd'
down_revision = 'bb706d3802ae'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('screens',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('issue_type_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['issue_type_id'], ['issue_types.id'], name=op.f('fk_screens_issue_type_id_issue_types'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_screens_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_screens')),
    sa.UniqueConstraint('project_id', 'issue_type_id', name=op.f('uq_screens_project_id_issue_type_id'))
    )
    op.create_index(op.f('ix_screens_project_id'), 'screens', ['project_id'], unique=False)
    op.create_index(op.f('ix_screens_workspace_id'), 'screens', ['workspace_id'], unique=False)
    op.create_table('screen_fields',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('screen_id', sa.Uuid(), nullable=False),
    sa.Column('field', sa.String(length=60), nullable=False),
    sa.Column('placement', sa.String(length=10), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['screen_id'], ['screens.id'], name=op.f('fk_screen_fields_screen_id_screens'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_screen_fields')),
    sa.UniqueConstraint('screen_id', 'field', name=op.f('uq_screen_fields_screen_id_field'))
    )
    op.create_index(op.f('ix_screen_fields_screen_id'), 'screen_fields', ['screen_id'], unique=False)
    # ix_doc_pages_fts drop stripped — functional GIN index alembic can't introspect (false positive).


def downgrade() -> None:
    op.drop_index(op.f('ix_screen_fields_screen_id'), table_name='screen_fields')
    op.drop_table('screen_fields')
    op.drop_index(op.f('ix_screens_workspace_id'), table_name='screens')
    op.drop_index(op.f('ix_screens_project_id'), table_name='screens')
    op.drop_table('screens')
    # ### end Alembic commands ###
