"""canned responses + sla tables (spec 30)

Revision ID: 2af6a5125285
Revises: b82af9418040

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '2af6a5125285'
down_revision = 'b82af9418040'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('canned_responses',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_canned_responses'))
    )
    op.create_index(op.f('ix_canned_responses_workspace_id'), 'canned_responses', ['workspace_id'], unique=False)
    op.create_table('sla_policies',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('response_minutes', sa.Integer(), nullable=True),
    sa.Column('resolution_minutes', sa.Integer(), nullable=True),
    sa.Column('pause_state_names', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_sla_policies_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sla_policies'))
    )
    op.create_index(op.f('ix_sla_policies_workspace_id'), 'sla_policies', ['workspace_id'], unique=False)
    op.create_table('sla_item_states',
    sa.Column('item_id', sa.Uuid(), nullable=False),
    sa.Column('policy_id', sa.Uuid(), nullable=False),
    sa.Column('response_due_at', sa.DateTime(), nullable=True),
    sa.Column('response_met_at', sa.DateTime(), nullable=True),
    sa.Column('response_breached_at', sa.DateTime(), nullable=True),
    sa.Column('resolution_due_at', sa.DateTime(), nullable=True),
    sa.Column('resolution_met_at', sa.DateTime(), nullable=True),
    sa.Column('resolution_breached_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['work_items.id'], name=op.f('fk_sla_item_states_item_id_work_items'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['policy_id'], ['sla_policies.id'], name=op.f('fk_sla_item_states_policy_id_sla_policies'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('item_id', 'policy_id', name=op.f('pk_sla_item_states'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sla_item_states')
    op.drop_index(op.f('ix_sla_policies_workspace_id'), table_name='sla_policies')
    op.drop_table('sla_policies')
    op.drop_index(op.f('ix_canned_responses_workspace_id'), table_name='canned_responses')
    op.drop_table('canned_responses')
    # ### end Alembic commands ###
