"""project keys globally unique (spec 21)

Revision ID: 2c9bd41c6a05
Revises: f01ce6ff3284

"""
from alembic import op
import sqlalchemy as sa


revision = '2c9bd41c6a05'
down_revision = 'f01ce6ff3284'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_projects_workspace_id_key'), 'projects', type_='unique')
    op.create_unique_constraint(op.f('uq_projects_key'), 'projects', ['key'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_projects_key'), 'projects', type_='unique')
    op.create_unique_constraint(op.f('uq_projects_workspace_id_key'), 'projects', ['workspace_id', 'key'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
