"""item archived_at (spec 38)

Revision ID: 313d9671a1d3
Revises: b86859928b9f

"""
from alembic import op
import sqlalchemy as sa


revision = '313d9671a1d3'
down_revision = 'b86859928b9f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('work_items', sa.Column('archived_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('work_items', 'archived_at')
    # ### end Alembic commands ###
