"""spec 90 jira import runs

Revision ID: 359b250bda3a
Revises: 5b7a489f873a

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '359b250bda3a'
down_revision = '5b7a489f873a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # Spec 90: one execution of an import — the progress row the wizard polls.
    # (Autogenerated ix_doc_pages_fts drop removed — expression-index false positive.)
    op.create_table('jira_import_runs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('plan_id', sa.Uuid(), nullable=True),
    sa.Column('actor_id', sa.Uuid(), nullable=False),
    sa.Column('jira_project_key', sa.String(length=100), nullable=False),
    sa.Column('jql', sa.Text(), nullable=False),
    sa.Column('radd_project_key', sa.String(length=20), nullable=False),
    sa.Column('radd_project_name', sa.String(length=200), nullable=False),
    sa.Column('field_mappings', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('stage', sa.String(length=20), nullable=False),
    sa.Column('counts', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('errors', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], name=op.f('fk_jira_import_runs_actor_id_users')),
    sa.ForeignKeyConstraint(['plan_id'], ['jira_import_plans.id'], name=op.f('fk_jira_import_runs_plan_id_jira_import_plans'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_jira_import_runs'))
    )


def downgrade() -> None:
    op.drop_table('jira_import_runs')
