"""spec 91: scopeable role grants (project_id)

Revision ID: 389293e3d799
Revises: 7c6a5417a89c

"""
from alembic import op
import sqlalchemy as sa


revision = '389293e3d799'
down_revision = '7c6a5417a89c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.add_column('global_role_grants', sa.Column('project_id', sa.Uuid(), nullable=True))
    op.drop_constraint(op.f('uq_global_role_grants_role_id_team_id'), 'global_role_grants', type_='unique')
    op.drop_constraint(op.f('uq_global_role_grants_role_id_user_id'), 'global_role_grants', type_='unique')
    op.create_index(op.f('ix_global_role_grants_project_id'), 'global_role_grants', ['project_id'], unique=False)
    op.create_unique_constraint(op.f('uq_global_role_grants_role_id_team_id_project_id'), 'global_role_grants', ['role_id', 'team_id', 'project_id'])
    op.create_unique_constraint(op.f('uq_global_role_grants_role_id_user_id_project_id'), 'global_role_grants', ['role_id', 'user_id', 'project_id'])
    op.create_foreign_key(op.f('fk_global_role_grants_project_id_projects'), 'global_role_grants', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_global_role_grants_project_id_projects'), 'global_role_grants', type_='foreignkey')
    op.drop_constraint(op.f('uq_global_role_grants_role_id_user_id_project_id'), 'global_role_grants', type_='unique')
    op.drop_constraint(op.f('uq_global_role_grants_role_id_team_id_project_id'), 'global_role_grants', type_='unique')
    op.drop_index(op.f('ix_global_role_grants_project_id'), table_name='global_role_grants')
    op.create_unique_constraint(op.f('uq_global_role_grants_role_id_user_id'), 'global_role_grants', ['role_id', 'user_id'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('uq_global_role_grants_role_id_team_id'), 'global_role_grants', ['role_id', 'team_id'], postgresql_nulls_not_distinct=False)
    op.drop_column('global_role_grants', 'project_id')
