"""spec 92: migrate builtin_field_rules to access_grants

Revision ID: 3d1e2f0f3823
Revises: 6fc5f7c71481

"""
from alembic import op
import sqlalchemy as sa


revision = '3d1e2f0f3823'
down_revision = '6fc5f7c71481'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # Move builtin-field rules into the generic table (spec 92): resource_type=
    # 'builtin_field', resource_id = the field name, scope kept as project_id.
    op.execute(
        """
        INSERT INTO access_grants (id, resource_type, resource_id, subject_type, subject_id, access, project_id)
        SELECT gen_random_uuid(), 'builtin_field', field, subject_type, subject_id, access, project_id
        FROM builtin_field_rules
        """
    )
    op.drop_index(op.f('ix_builtin_field_rules_project_id'), table_name='builtin_field_rules')
    op.drop_table('builtin_field_rules')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('builtin_field_rules',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('project_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('field', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('subject_type', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('subject_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('access', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_builtin_field_rules_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_builtin_field_rules')),
    sa.UniqueConstraint('project_id', 'field', 'subject_type', 'subject_id', 'access', name=op.f('uq_builtin_field_rules_scope'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_builtin_field_rules_project_id'), 'builtin_field_rules', ['project_id'], unique=False)
    # ### end Alembic commands ###
