"""spec 87 stage 1 global role grants

Revision ID: 466eca47eeee
Revises: f4a9c31e77d2

"""
from alembic import op
import sqlalchemy as sa


revision = '466eca47eeee'
down_revision = 'f4a9c31e77d2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # Spec 87: the delivery mechanism for global-scope permission atoms — a role
    # held instance-wide by a user or a team. (The autogenerated drop of
    # ix_doc_pages_fts was removed: alembic cannot see expression indexes and
    # re-proposes it on every run.)
    op.create_table('global_role_grants',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('role_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('team_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name=op.f('fk_global_role_grants_role_id_roles')),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], name=op.f('fk_global_role_grants_team_id_teams'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_global_role_grants_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_global_role_grants')),
    sa.UniqueConstraint('role_id', 'team_id', name=op.f('uq_global_role_grants_role_id_team_id')),
    sa.UniqueConstraint('role_id', 'user_id', name=op.f('uq_global_role_grants_role_id_user_id')),
    # Exactly one subject per grant — the view_shares invariant, enforced in the DB
    # so a bad writer can't create a row that resolves against nobody (or everybody).
    sa.CheckConstraint(
        '(user_id IS NULL) <> (team_id IS NULL)',
        name=op.f('ck_global_role_grants_one_subject'),
    )
    )
    op.create_index(op.f('ix_global_role_grants_role_id'), 'global_role_grants', ['role_id'], unique=False)
    op.create_index(op.f('ix_global_role_grants_team_id'), 'global_role_grants', ['team_id'], unique=False)
    op.create_index(op.f('ix_global_role_grants_user_id'), 'global_role_grants', ['user_id'], unique=False)


def downgrade() -> None:
    op.drop_index(op.f('ix_global_role_grants_user_id'), table_name='global_role_grants')
    op.drop_index(op.f('ix_global_role_grants_team_id'), table_name='global_role_grants')
    op.drop_index(op.f('ix_global_role_grants_role_id'), table_name='global_role_grants')
    op.drop_table('global_role_grants')
    # ### end Alembic commands ###
