"""form shares (spec 73)

Revision ID: 48979a48f5b6
Revises: 4e66edf3f951

"""
from alembic import op
import sqlalchemy as sa


revision = '48979a48f5b6'
down_revision = '4e66edf3f951'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('form_shares',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('form_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('team_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('(user_id IS NULL) != (team_id IS NULL)', name=op.f('ck_form_shares_one_subject')),
    sa.ForeignKeyConstraint(['form_id'], ['forms.id'], name=op.f('fk_form_shares_form_id_forms'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], name=op.f('fk_form_shares_team_id_teams'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_form_shares_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_form_shares')),
    sa.UniqueConstraint('form_id', 'team_id', name=op.f('uq_form_shares_form_id_team_id')),
    sa.UniqueConstraint('form_id', 'user_id', name=op.f('uq_form_shares_form_id_user_id'))
    )
    op.create_index(op.f('ix_form_shares_form_id'), 'form_shares', ['form_id'], unique=False)
    op.create_index(op.f('ix_form_shares_team_id'), 'form_shares', ['team_id'], unique=False)
    op.create_index(op.f('ix_form_shares_user_id'), 'form_shares', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_form_shares_user_id'), table_name='form_shares')
    op.drop_index(op.f('ix_form_shares_team_id'), table_name='form_shares')
    op.drop_index(op.f('ix_form_shares_form_id'), table_name='form_shares')
    op.drop_table('form_shares')
    # ### end Alembic commands ###
