"""forms intake

Revision ID: 48b0a4ae4291
Revises: e4390d7d9542

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '48b0a4ae4291'
down_revision = 'e4390d7d9542'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('forms',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('fields', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('defaults', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('title_prompt', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_forms_project_id_projects')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_forms'))
    )
    op.create_index(op.f('ix_forms_project_id'), 'forms', ['project_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_forms_project_id'), table_name='forms')
    op.drop_table('forms')
    # ### end Alembic commands ###
