"""participants (spec 72)

Revision ID: 4e66edf3f951
Revises: ea8e44297500

"""
from alembic import op
import sqlalchemy as sa


revision = '4e66edf3f951'
down_revision = 'ea8e44297500'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('item_participants',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('item_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('team_id', sa.Uuid(), nullable=True),
    sa.Column('added_by', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('(user_id IS NULL) != (team_id IS NULL)', name=op.f('ck_item_participants_one_subject')),
    sa.ForeignKeyConstraint(['added_by'], ['users.id'], name=op.f('fk_item_participants_added_by_users')),
    sa.ForeignKeyConstraint(['item_id'], ['work_items.id'], name=op.f('fk_item_participants_item_id_work_items'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], name=op.f('fk_item_participants_team_id_teams'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_item_participants_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_item_participants')),
    sa.UniqueConstraint('item_id', 'team_id', name=op.f('uq_item_participants_item_id_team_id')),
    sa.UniqueConstraint('item_id', 'user_id', name=op.f('uq_item_participants_item_id_user_id'))
    )
    op.create_index(op.f('ix_item_participants_item_id'), 'item_participants', ['item_id'], unique=False)
    op.create_index(op.f('ix_item_participants_team_id'), 'item_participants', ['team_id'], unique=False)
    op.create_index(op.f('ix_item_participants_user_id'), 'item_participants', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_item_participants_user_id'), table_name='item_participants')
    op.drop_index(op.f('ix_item_participants_team_id'), table_name='item_participants')
    op.drop_index(op.f('ix_item_participants_item_id'), table_name='item_participants')
    op.drop_table('item_participants')
    # ### end Alembic commands ###
