"""workflow transitions

Revision ID: 57614f09f956
Revises: 8325cd80bd6d

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '57614f09f956'
down_revision = '8325cd80bd6d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workflow_transitions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('from_state_id', sa.Uuid(), nullable=True),
    sa.Column('to_state_id', sa.Uuid(), nullable=False),
    sa.Column('rules', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['from_state_id'], ['states.id'], name=op.f('fk_workflow_transitions_from_state_id_states')),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_workflow_transitions_project_id_projects'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['to_state_id'], ['states.id'], name=op.f('fk_workflow_transitions_to_state_id_states')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_workflow_transitions'))
    )
    op.create_index(op.f('ix_workflow_transitions_project_id'), 'workflow_transitions', ['project_id'], unique=False)
    # (stripped: autogenerate's known ix_doc_pages_fts false-positive drop)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_workflow_transitions_project_id'), table_name='workflow_transitions')
    op.drop_table('workflow_transitions')
    # ### end Alembic commands ###
