"""spec 90 jira import plans

Revision ID: 5b7a489f873a
Revises: 78c86f700dbe

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '5b7a489f873a'
down_revision = '78c86f700dbe'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # Spec 90: a reusable Jira import configuration (project + JQL + field
    # mappings). The autogenerated drop of ix_doc_pages_fts was removed — alembic
    # can't see the expression index and re-proposes it every run.
    op.create_table('jira_import_plans',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('jira_project_key', sa.String(length=100), nullable=False),
    sa.Column('jql', sa.Text(), nullable=False),
    sa.Column('radd_project_key', sa.String(length=20), nullable=False),
    sa.Column('radd_project_name', sa.String(length=200), nullable=False),
    sa.Column('field_mappings', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_jira_import_plans')),
    sa.UniqueConstraint('name', name=op.f('uq_jira_import_plans_name'))
    )


def downgrade() -> None:
    op.drop_table('jira_import_plans')
