"""cycle series

Revision ID: 5df5c6f35ec7
Revises: bda2d16f2533

"""
from alembic import op
import sqlalchemy as sa


revision = '5df5c6f35ec7'
down_revision = 'bda2d16f2533'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cycle_series',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('label', sa.String(length=180), nullable=False),
    sa.Column('drafts_ahead', sa.Integer(), nullable=False),
    sa.Column('next_number', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_cycle_series_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cycle_series')),
    sa.UniqueConstraint('workspace_id', 'label', name=op.f('uq_cycle_series_workspace_id_label'))
    )
    op.create_index(op.f('ix_cycle_series_workspace_id'), 'cycle_series', ['workspace_id'], unique=False)
    # (alembic's usual false-positive drop of ix_doc_pages_fts stripped — see PLAN §11)


def downgrade() -> None:
    op.drop_index(op.f('ix_cycle_series_workspace_id'), table_name='cycle_series')
    op.drop_table('cycle_series')
