"""view sharing: workspace_access + view_shares (spec 57)

Revision ID: 5e4a41d09ca0
Revises: c536f26534fb

"""
from alembic import op
import sqlalchemy as sa


revision = '5e4a41d09ca0'
down_revision = 'c536f26534fb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('view_shares',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('view_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('team_id', sa.Uuid(), nullable=True),
    sa.Column('level', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], name=op.f('fk_view_shares_team_id_teams'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_view_shares_user_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['view_id'], ['views.id'], name=op.f('fk_view_shares_view_id_views'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_view_shares'))
    )
    op.create_index(op.f('ix_view_shares_team_id'), 'view_shares', ['team_id'], unique=False)
    op.create_index(op.f('ix_view_shares_user_id'), 'view_shares', ['user_id'], unique=False)
    op.create_index(op.f('ix_view_shares_view_id'), 'view_shares', ['view_id'], unique=False)
    op.add_column('views', sa.Column('workspace_access', sa.String(length=10), nullable=True))
    # Legacy workspace-shared views (owner_id NULL) stay visible to every member
    # at viewer level; edit/manage keeps flowing through the view.* RBAC atoms.
    op.execute("UPDATE views SET workspace_access = 'viewer' WHERE owner_id IS NULL")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('views', 'workspace_access')
    op.drop_index(op.f('ix_view_shares_view_id'), table_name='view_shares')
    op.drop_index(op.f('ix_view_shares_user_id'), table_name='view_shares')
    op.drop_index(op.f('ix_view_shares_team_id'), table_name='view_shares')
    op.drop_table('view_shares')
    # ### end Alembic commands ###
