"""issue types spec 51

Revision ID: 643a19d63157
Revises: 70e65e295c4f

"""
from alembic import op
import sqlalchemy as sa


revision = '643a19d63157'
down_revision = '70e65e295c4f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('issue_types',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('color', sa.String(length=7), nullable=False),
    sa.Column('icon', sa.String(length=40), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_issue_types_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_issue_types')),
    sa.UniqueConstraint('project_id', 'name', name=op.f('uq_issue_types_project_id_name'))
    )
    op.create_index(op.f('ix_issue_types_project_id'), 'issue_types', ['project_id'], unique=False)
    # NOTE: autogenerate's ix_doc_pages_fts drop is a false positive (functional GIN
    # index it can't introspect) — omitted on purpose.
    op.add_column('work_items', sa.Column('type_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_work_items_type_id'), 'work_items', ['type_id'], unique=False)
    op.create_foreign_key(op.f('fk_work_items_type_id_issue_types'), 'work_items', 'issue_types', ['type_id'], ['id'], ondelete='SET NULL')

    # Backfill: seed the default type set into every EXISTING project (the
    # project.created hook only covers new projects), then type every existing item
    # with its project's default (Task). Keep in sync with itemtypes.types.DEFAULT_TYPES.
    op.execute(
        """
        INSERT INTO issue_types (id, project_id, name, color, icon, position, is_default, created_at, updated_at)
        SELECT gen_random_uuid(), p.id, t.name, t.color, t.icon, t.position, t.is_default, now(), now()
        FROM projects p
        CROSS JOIN (VALUES
          ('Task', '#64748b', 'square-check-big', 1, true),
          ('Bug', '#ef4444', 'bug', 2, false),
          ('Story', '#22c55e', 'bookmark', 3, false),
          ('Feature', '#3b82f6', 'sparkles', 4, false),
          ('Epic', '#a855f7', 'gem', 5, false)
        ) AS t(name, color, icon, position, is_default)
        """
    )
    op.execute(
        """
        UPDATE work_items w SET type_id = it.id
        FROM issue_types it
        WHERE it.project_id = w.project_id AND it.is_default = true AND w.type_id IS NULL
        """
    )
    # spec 51: admin (= all project-scoped perms) gains the issue_type CRUD atoms.
    for value in ("issue_type.create", "issue_type.update", "issue_type.delete"):
        op.execute(
            f"""
            UPDATE roles SET permissions = permissions || '["{value}"]'::jsonb
            WHERE is_builtin AND key = 'admin' AND NOT permissions @> '["{value}"]'::jsonb
            """
        )


def downgrade() -> None:
    for value in ("issue_type.create", "issue_type.update", "issue_type.delete"):
        op.execute(f"UPDATE roles SET permissions = permissions - '{value}' WHERE is_builtin AND key = 'admin'")
    op.drop_constraint(op.f('fk_work_items_type_id_issue_types'), 'work_items', type_='foreignkey')
    op.drop_index(op.f('ix_work_items_type_id'), table_name='work_items')
    op.drop_column('work_items', 'type_id')
    op.drop_index(op.f('ix_issue_types_project_id'), table_name='issue_types')
    op.drop_table('issue_types')
