"""ai provider registry spec 101

Revision ID: 6769faf965b9
Revises: d7e02c4a5b13

"""
from alembic import op
import sqlalchemy as sa

revision = '6769faf965b9'
down_revision = 'd7e02c4a5b13'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_preset_prompts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('enabled', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ai_preset_prompts'))
    )
    op.create_table('ai_providers',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('wire_shape', sa.String(length=20), nullable=False),
    sa.Column('base_url', sa.String(length=500), nullable=False),
    sa.Column('api_key', sa.Text(), nullable=False),
    sa.Column('default_model', sa.String(length=200), nullable=False),
    sa.Column('source', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ai_providers')),
    sa.UniqueConstraint('name', name=op.f('uq_ai_providers_name'))
    )
    op.create_table('ai_model_roles',
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('provider_id', sa.Uuid(), nullable=False),
    sa.Column('model', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['provider_id'], ['ai_providers.id'], name=op.f('fk_ai_model_roles_provider_id_ai_providers'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('role', name=op.f('pk_ai_model_roles'))
    )
    # False-positive drops stripped (acme_notes example plugin, backup partial
    # indexes, the doc_pages functional FTS index — Alembic can't introspect them).
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ai_model_roles')
    op.drop_table('ai_providers')
    op.drop_table('ai_preset_prompts')
    # ### end Alembic commands ###
