"""spec 92: generic access_grants; migrate field_permissions

Revision ID: 6fc5f7c71481
Revises: 389293e3d799

"""
from alembic import op
import sqlalchemy as sa


revision = '6fc5f7c71481'
down_revision = '389293e3d799'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('access_grants',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('resource_type', sa.String(length=40), nullable=False),
    sa.Column('resource_id', sa.String(length=100), nullable=False),
    sa.Column('subject_type', sa.String(length=10), nullable=False),
    sa.Column('subject_id', sa.Uuid(), nullable=False),
    sa.Column('access', sa.String(length=20), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_access_grants_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_access_grants')),
    sa.UniqueConstraint('resource_type', 'resource_id', 'subject_type', 'subject_id', 'access', 'project_id', name='uq_access_grants_row')
    )
    op.create_index(op.f('ix_access_grants_project_id'), 'access_grants', ['project_id'], unique=False)
    op.create_index('ix_access_grants_resource', 'access_grants', ['resource_type', 'resource_id'], unique=False)
    op.create_index(op.f('ix_access_grants_subject_id'), 'access_grants', ['subject_id'], unique=False)
    # Move existing custom-field grants (spec 07/92) into the generic table: a global
    # (project_id NULL) read/write grant per row, resource_type='field'.
    op.execute(
        """
        INSERT INTO access_grants (id, resource_type, resource_id, subject_type, subject_id, access, project_id)
        SELECT gen_random_uuid(), 'field', field_id::text, subject_type, subject_id, access, NULL
        FROM field_permissions
        """
    )
    op.drop_index(op.f('ix_field_permissions_field_id'), table_name='field_permissions')
    op.drop_table('field_permissions')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('field_permissions',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('field_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('subject_type', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('subject_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('access', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['field_id'], ['field_definitions.id'], name=op.f('fk_field_permissions_field_id_field_definitions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_field_permissions')),
    sa.UniqueConstraint('field_id', 'subject_type', 'subject_id', 'access', name=op.f('uq_field_permissions_field_id_subject_type_subject_id_access'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_field_permissions_field_id'), 'field_permissions', ['field_id'], unique=False)
    op.drop_index(op.f('ix_access_grants_subject_id'), table_name='access_grants')
    op.drop_index('ix_access_grants_resource', table_name='access_grants')
    op.drop_index(op.f('ix_access_grants_project_id'), table_name='access_grants')
    op.drop_table('access_grants')
    # ### end Alembic commands ###
