"""comment visibility teams spec 50

Revision ID: 70e65e295c4f
Revises: 5a53e459d033

"""
from alembic import op
import sqlalchemy as sa


revision = '70e65e295c4f'
down_revision = '5a53e459d033'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comment_visibility_teams',
    sa.Column('comment_id', sa.Uuid(), nullable=False),
    sa.Column('team_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['comment_id'], ['comments.id'], name=op.f('fk_comment_visibility_teams_comment_id_comments'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], name=op.f('fk_comment_visibility_teams_team_id_teams'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('comment_id', 'team_id', name=op.f('pk_comment_visibility_teams'))
    )
    # NOTE: autogenerate's ix_doc_pages_fts drop is a false positive (functional GIN
    # index it can't introspect) — omitted on purpose.


def downgrade() -> None:
    op.drop_table('comment_visibility_teams')
    # ### end Alembic commands ###
