"""spec 87 stage 2-3 team source ownership managers

Revision ID: 78c86f700dbe
Revises: 3a363a121502

"""
from alembic import op
import sqlalchemy as sa


revision = '78c86f700dbe'
down_revision = '3a363a121502'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # Spec 87: teams gain a membership-ownership state (TeamSource), an owner, a
    # manager table for delegated per-team administration, and a stale-group flag.
    # (The autogenerated drop of ix_doc_pages_fts was removed: alembic cannot see
    # expression indexes and re-proposes it on every run.)
    op.create_table('team_managers',
    sa.Column('team_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], name=op.f('fk_team_managers_team_id_teams'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_team_managers_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('team_id', 'user_id', name=op.f('pk_team_managers'))
    )
    op.add_column('teams', sa.Column('directory_missing_since', sa.DateTime(), nullable=True))
    op.add_column('teams', sa.Column('source', sa.String(length=20), server_default='local', nullable=False))
    op.add_column('teams', sa.Column('owner_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_teams_owner_id'), 'teams', ['owner_id'], unique=False)
    op.create_foreign_key(op.f('fk_teams_owner_id_users'), 'teams', 'users', ['owner_id'], ['id'], ondelete='SET NULL')

    # Every already-linked team is directory-owned: that is what the link meant.
    op.execute(
        "UPDATE teams SET source = 'directory' WHERE directory_group_dn IS NOT NULL"
    )
    # Deliberately NOT re-sourcing existing team_members rows. Under spec 84 a
    # linked team could hold hand-added rows alongside synced ones; converting
    # those to `directory` here would let the next reconcile delete anyone absent
    # from the AD group, i.e. an upgrade that silently revokes access. They stay
    # `manual` and simply survive — an admin who wants them gone unlinks the team
    # (which converts the roster back to manual) or removes them in AD. Going
    # forward, linking re-sources the roster explicitly as a deliberate act.

    # Pre-87 teams have no owner (owner_id NULL). That is a supported state, not a
    # gap to fill: those teams fall back to the team.update/team.delete atoms, and
    # guessing an owner from the member list would hand someone real authority.


def downgrade() -> None:
    op.drop_constraint(op.f('fk_teams_owner_id_users'), 'teams', type_='foreignkey')
    op.drop_index(op.f('ix_teams_owner_id'), table_name='teams')
    op.drop_column('teams', 'owner_id')
    op.drop_column('teams', 'source')
    op.drop_column('teams', 'directory_missing_since')
    op.drop_table('team_managers')
