"""scheduled automations + sla due_soon (spec 69)

Revision ID: 7b7fa7839f55
Revises: f7392cb631ca

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '7b7fa7839f55'
down_revision = 'f7392cb631ca'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('automation_schedule_state',
    sa.Column('rule_id', sa.Uuid(), nullable=False),
    sa.Column('next_run_at', sa.DateTime(), nullable=False),
    sa.Column('last_run_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['rule_id'], ['automation_rules.id'], name=op.f('fk_automation_schedule_state_rule_id_automation_rules'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('rule_id', name=op.f('pk_automation_schedule_state'))
    )
    op.add_column('automation_rules', sa.Column('schedule', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('sla_item_states', sa.Column('warned_response_at', sa.DateTime(), nullable=True))
    op.add_column('sla_item_states', sa.Column('warned_resolution_at', sa.DateTime(), nullable=True))
    op.add_column('sla_policies', sa.Column('warning_minutes', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sla_policies', 'warning_minutes')
    op.drop_column('sla_item_states', 'warned_resolution_at')
    op.drop_column('sla_item_states', 'warned_response_at')
    op.drop_column('automation_rules', 'schedule')
    op.drop_table('automation_schedule_state')
    # ### end Alembic commands ###
