"""mail contacts + public forms (spec 62)

Revision ID: 7be36ff1ac2c
Revises: 57614f09f956

"""
from alembic import op
import sqlalchemy as sa


revision = '7be36ff1ac2c'
down_revision = '57614f09f956'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mail_contacts',
    sa.Column('item_id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('last_message_id', sa.String(length=998), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['work_items.id'], name=op.f('fk_mail_contacts_item_id_work_items'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('item_id', name=op.f('pk_mail_contacts'))
    )
    # (stripped: autogenerate's known ix_doc_pages_fts false-positive drop)
    op.add_column(
        'forms',
        sa.Column('allow_public', sa.Boolean(), nullable=False, server_default=sa.false()),
    )
    op.add_column('forms', sa.Column('public_token', sa.String(length=64), nullable=True))
    op.create_unique_constraint(op.f('uq_forms_public_token'), 'forms', ['public_token'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_forms_public_token'), 'forms', type_='unique')
    op.drop_column('forms', 'public_token')
    op.drop_column('forms', 'allow_public')
    op.drop_table('mail_contacts')
    # ### end Alembic commands ###
