"""spec 91: user-definable issue link types

Revision ID: 7c6a5417a89c
Revises: 8dc68ca67b05

"""
from alembic import op
import sqlalchemy as sa


revision = '7c6a5417a89c'
down_revision = '8dc68ca67b05'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('item_link_types',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('key', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.Column('outward_name', sa.String(length=60), nullable=False),
    sa.Column('inward_name', sa.String(length=60), nullable=False),
    sa.Column('direction', sa.String(length=20), nullable=False),
    sa.Column('system', sa.Boolean(), nullable=False),
    sa.Column('auto_managed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_item_link_types')),
    sa.UniqueConstraint('key', name=op.f('uq_item_link_types_key'))
    )
    op.create_table('item_link_type_projects',
    sa.Column('link_type_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['link_type_id'], ['item_link_types.id'], name=op.f('fk_item_link_type_projects_link_type_id_item_link_types'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_item_link_type_projects_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('link_type_id', 'project_id', name=op.f('pk_item_link_type_projects'))
    )
    # Seed the built-in types (idempotent — the app also ensures them on startup) so a
    # fresh DB has a working catalog. Keys match the values already on `item_links`.
    op.execute(
        """
        INSERT INTO item_link_types (id, key, name, outward_name, inward_name, direction, system, auto_managed)
        VALUES
          (gen_random_uuid(), 'blocks', 'Blocks', 'blocks', 'is blocked by', 'directed', true, false),
          (gen_random_uuid(), 'relates', 'Relates', 'relates to', 'relates to', 'symmetric', true, false),
          (gen_random_uuid(), 'duplicates', 'Duplicates', 'duplicates', 'is duplicated by', 'directed', true, false),
          (gen_random_uuid(), 'mentions', 'Mentions', 'mentions', 'mentioned by', 'directed', true, true)
        ON CONFLICT (key) DO NOTHING
        """
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    op.drop_table('item_link_type_projects')
    op.drop_table('item_link_types')
    # ### end Alembic commands ###
