"""comments become polymorphic (RADD-717)

Revision ID: 802d80435ed9
Revises: 3f09527aef0e
Create Date: 2026-08-03 00:27:29.030195

`comments.item_id` (FK -> work_items, ON DELETE CASCADE) becomes
`entity_type` + `entity_id`, so a page can own a comment.

Hand-written rather than autogenerated, for two reasons. Autogenerate proposes
dropping the runtime-managed embeddings tables on every run (spec 103 keeps them
out of Base.metadata deliberately). And a generated column swap would drop the
old column before the new one is populated — the backfill has to happen in
between, which is the entire risk in this change.

**The cascade is deliberately given up.** A polymorphic column cannot carry a
foreign key, so deleting an item or a page no longer takes its comments with it.
Both hard-delete paths now call `comments.service.delete_for_parent` instead.
That is a worse guarantee than the database gave us, and it is the price of the
feature; the alternative — a nullable FK per parent type — turns every new
parent into a schema change and a wider table.
"""
from alembic import op
import sqlalchemy as sa

revision = '802d80435ed9'
down_revision = '3f09527aef0e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # 1. Add nullable, so existing rows survive the statement.
    op.add_column('comments', sa.Column('entity_type', sa.String(length=30),
                                        nullable=False, server_default='item'))
    op.add_column('comments', sa.Column('entity_id', sa.Uuid(), nullable=True))

    # 2. Backfill: every comment that exists today is on an item.
    op.execute(sa.text("UPDATE comments SET entity_id = item_id WHERE entity_id IS NULL"))

    # 3. Only now can it be NOT NULL.
    op.alter_column('comments', 'entity_id', nullable=False)

    # 4. The old column goes, with its index and FK.
    op.drop_index('ix_comments_item_id', table_name='comments')
    op.drop_column('comments', 'item_id')

    # 5. The read that matters: every comment on one parent, in order.
    op.create_index('ix_comments_parent', 'comments', ['entity_type', 'entity_id'], unique=False)
    op.create_index(op.f('ix_comments_entity_id'), 'comments', ['entity_id'], unique=False)


def downgrade() -> None:
    """Reversible only while every comment is still on an item — which is true
    until the first page comment is written. Refuse rather than silently drop
    them: losing a discussion to a downgrade is not an acceptable outcome."""
    stranded = op.get_bind().execute(
        sa.text("SELECT count(*) FROM comments WHERE entity_type <> 'item'")
    ).scalar_one()
    if stranded:
        raise RuntimeError(
            f"{stranded} comment(s) are attached to non-item parents; downgrading would "
            "delete them. Remove or re-home them first."
        )
    op.add_column('comments', sa.Column('item_id', sa.Uuid(), nullable=True))
    op.execute(sa.text("UPDATE comments SET item_id = entity_id"))
    op.alter_column('comments', 'item_id', nullable=False)
    op.create_foreign_key(
        'fk_comments_item_id_work_items', 'comments', 'work_items',
        ['item_id'], ['id'], ondelete='CASCADE',
    )
    op.create_index('ix_comments_item_id', 'comments', ['item_id'], unique=False)
    op.drop_index(op.f('ix_comments_entity_id'), table_name='comments')
    op.drop_index('ix_comments_parent', table_name='comments')
    op.drop_column('comments', 'entity_id')
    op.drop_column('comments', 'entity_type')
