"""cycle_teams: team-restricted cycle visibility (spec 60)

Revision ID: 8325cd80bd6d
Revises: 43a780816f08

"""
from alembic import op
import sqlalchemy as sa


revision = '8325cd80bd6d'
down_revision = '43a780816f08'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cycle_teams',
    sa.Column('cycle_id', sa.Uuid(), nullable=False),
    sa.Column('team_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['cycle_id'], ['cycles.id'], name=op.f('fk_cycle_teams_cycle_id_cycles'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], name=op.f('fk_cycle_teams_team_id_teams'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('cycle_id', 'team_id', name=op.f('pk_cycle_teams'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cycle_teams')
    # ### end Alembic commands ###
