"""ad integration depth (spec 84)

- `users.source` (UserSource: local|ldap|oidc|unknown) + `users.last_login_at`.
  Backfill: a password hash means a local account; everything else (SSO-only
  rows predating this spec) starts `unknown` and is claimed by the next
  LDAP/OIDC login. New rows set source at their creation point.
- `teams.directory_group_dn`/`directory_group_name` — the AD group link
  (nested membership honored via the transitive matching rule).
- `team_members.source` (MemberSource: manual|directory) — directory sync owns
  ONLY its own rows; hand-added members survive every reconcile.

Revision ID: 8dcb99d261e6
Revises: d1f80c2eedc3

"""
from alembic import op
import sqlalchemy as sa


revision = '8dcb99d261e6'
down_revision = 'd1f80c2eedc3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('team_members', sa.Column('source', sa.String(length=20), server_default='manual', nullable=False))
    op.add_column('teams', sa.Column('directory_group_dn', sa.Text(), nullable=True))
    op.add_column('teams', sa.Column('directory_group_name', sa.String(length=200), nullable=True))
    op.add_column('users', sa.Column('source', sa.String(length=20), server_default='unknown', nullable=False))
    op.add_column('users', sa.Column('last_login_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###
    # Backfill (spec 84): a stored password hash marks a local account; the
    # rest are pre-84 SSO-only rows — 'unknown' until their next directory login.
    op.execute("UPDATE users SET source = 'local' WHERE password_hash IS NOT NULL")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_login_at')
    op.drop_column('users', 'source')
    op.drop_column('teams', 'directory_group_name')
    op.drop_column('teams', 'directory_group_dn')
    op.drop_column('team_members', 'source')
    # ### end Alembic commands ###
