"""dashboards (spec 75)

Composable dashboards: `dashboards` (ownership + spec-57 sharing vocabulary),
`dashboard_shares` (exactly-one-of user/team CHECK, the item_participants
idiom), `dashboard_widgets` (typed JSONB configs over existing read surfaces).

Also mirrors the three new GLOBAL dashboard.* atoms into existing builtin
`admin` role rows (the 41196e02047c JSONB-append pattern) — the seeded admin
definition now carries them as global-scoped riders (the doc.write-on-member
precedent), so seeds and stored rows stay identical and the roles matrix stays
truthful. Correctness never depends on this: workspace.manage implies the
atoms via umbrella expansion, and global-scope checks key on workspace
membership, not project roles.

Revision ID: 9176930be113
Revises: 7a1827897d5c

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '9176930be113'
down_revision = '7a1827897d5c'
branch_labels = None
depends_on = None

# The spec-75 dashboard atoms, appended to stored builtin admin rows so the
# rows keep mirroring the seeded definition (immutability contract).
_ADMIN_ADDS = (
    "dashboard.create",
    "dashboard.update",
    "dashboard.delete",
)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dashboards',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=True),
    sa.Column('workspace_access', sa.String(length=10), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('fk_dashboards_owner_id_users')),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_dashboards_workspace_id_workspaces')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_dashboards'))
    )
    op.create_index(op.f('ix_dashboards_owner_id'), 'dashboards', ['owner_id'], unique=False)
    op.create_index(op.f('ix_dashboards_workspace_id'), 'dashboards', ['workspace_id'], unique=False)
    op.create_table('dashboard_shares',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('dashboard_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('team_id', sa.Uuid(), nullable=True),
    sa.Column('level', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('(user_id IS NULL) != (team_id IS NULL)', name=op.f('ck_dashboard_shares_one_subject')),
    sa.ForeignKeyConstraint(['dashboard_id'], ['dashboards.id'], name=op.f('fk_dashboard_shares_dashboard_id_dashboards'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], name=op.f('fk_dashboard_shares_team_id_teams'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_dashboard_shares_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_dashboard_shares')),
    sa.UniqueConstraint('dashboard_id', 'team_id', name=op.f('uq_dashboard_shares_dashboard_id_team_id')),
    sa.UniqueConstraint('dashboard_id', 'user_id', name=op.f('uq_dashboard_shares_dashboard_id_user_id'))
    )
    op.create_index(op.f('ix_dashboard_shares_dashboard_id'), 'dashboard_shares', ['dashboard_id'], unique=False)
    op.create_index(op.f('ix_dashboard_shares_team_id'), 'dashboard_shares', ['team_id'], unique=False)
    op.create_index(op.f('ix_dashboard_shares_user_id'), 'dashboard_shares', ['user_id'], unique=False)
    op.create_table('dashboard_widgets',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('dashboard_id', sa.Uuid(), nullable=False),
    sa.Column('widget_type', sa.String(length=30), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('width', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['dashboard_id'], ['dashboards.id'], name=op.f('fk_dashboard_widgets_dashboard_id_dashboards'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_dashboard_widgets'))
    )
    op.create_index(op.f('ix_dashboard_widgets_dashboard_id'), 'dashboard_widgets', ['dashboard_id'], unique=False)
    # ### end Alembic commands ###
    for value in _ADMIN_ADDS:
        op.execute(
            f"""
            UPDATE roles
            SET permissions = permissions || '["{value}"]'::jsonb
            WHERE is_builtin AND key = 'admin'
              AND NOT permissions @> '["{value}"]'::jsonb
            """
        )


def downgrade() -> None:
    for value in _ADMIN_ADDS:
        op.execute(
            f"""
            UPDATE roles
            SET permissions = permissions - '{value}'
            WHERE is_builtin AND key = 'admin'
            """
        )
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_dashboard_widgets_dashboard_id'), table_name='dashboard_widgets')
    op.drop_table('dashboard_widgets')
    op.drop_index(op.f('ix_dashboard_shares_user_id'), table_name='dashboard_shares')
    op.drop_index(op.f('ix_dashboard_shares_team_id'), table_name='dashboard_shares')
    op.drop_index(op.f('ix_dashboard_shares_dashboard_id'), table_name='dashboard_shares')
    op.drop_table('dashboard_shares')
    op.drop_index(op.f('ix_dashboards_workspace_id'), table_name='dashboards')
    op.drop_index(op.f('ix_dashboards_owner_id'), table_name='dashboards')
    op.drop_table('dashboards')
    # ### end Alembic commands ###
