"""spec 92: migrate view_shares to access_grants

Revision ID: 925809931622
Revises: 3d1e2f0f3823

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '925809931622'
down_revision = '3d1e2f0f3823'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # Move view shares into the generic table (spec 92): resource_type='view',
    # resource_id = the view id, subject user/team, access = the ShareLevel.
    op.execute(
        """
        INSERT INTO access_grants (id, resource_type, resource_id, subject_type, subject_id, access, project_id)
        SELECT gen_random_uuid(), 'view', view_id::text,
               CASE WHEN user_id IS NOT NULL THEN 'user' ELSE 'team' END,
               COALESCE(user_id, team_id), level, NULL
        FROM view_shares
        """
    )
    op.drop_index(op.f('ix_view_shares_team_id'), table_name='view_shares')
    op.drop_index(op.f('ix_view_shares_user_id'), table_name='view_shares')
    op.drop_index(op.f('ix_view_shares_view_id'), table_name='view_shares')
    op.drop_table('view_shares')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('view_shares',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('view_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('team_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('level', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], name=op.f('fk_view_shares_team_id_teams'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_view_shares_user_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['view_id'], ['views.id'], name=op.f('fk_view_shares_view_id_views'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_view_shares'))
    )
    op.create_index(op.f('ix_view_shares_view_id'), 'view_shares', ['view_id'], unique=False)
    op.create_index(op.f('ix_view_shares_user_id'), 'view_shares', ['user_id'], unique=False)
    op.create_index(op.f('ix_view_shares_team_id'), 'view_shares', ['team_id'], unique=False)
    # ### end Alembic commands ###
