"""search: FTS index table

Revision ID: 96d3375c5496
Revises: db3ad0f8de3f

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '96d3375c5496'
down_revision = 'db3ad0f8de3f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('search_index',
    sa.Column('item_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('key', sa.String(length=30), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('comments_text', sa.Text(), nullable=False),
    sa.Column('tsv', postgresql.TSVECTOR(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['work_items.id'], name=op.f('fk_search_index_item_id_work_items'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('item_id', name=op.f('pk_search_index'))
    )
    op.create_index(op.f('ix_search_index_project_id'), 'search_index', ['project_id'], unique=False)
    op.create_index('ix_search_index_tsv', 'search_index', ['tsv'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_search_index_workspace_id'), 'search_index', ['workspace_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_search_index_workspace_id'), table_name='search_index')
    op.drop_index('ix_search_index_tsv', table_name='search_index', postgresql_using='gin')
    op.drop_index(op.f('ix_search_index_project_id'), table_name='search_index')
    op.drop_table('search_index')
    # ### end Alembic commands ###
