"""notification prefs

Revision ID: 9a829dc79eef
Revises: 229e9d3c413b

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '9a829dc79eef'
down_revision = '229e9d3c413b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification_prefs',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('muted_types', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('email_digest', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('user_id', name=op.f('pk_notification_prefs'))
    )
    # (alembic's usual false-positive drop of ix_doc_pages_fts stripped — see PLAN §11)


def downgrade() -> None:
    op.drop_table('notification_prefs')
