"""timelogging: worklogs, estimates, work categories, per-project enablement (spec 22)

Revision ID: b154d8429f77
Revises: 2c9bd41c6a05

"""
from alembic import op
import sqlalchemy as sa


revision = 'b154d8429f77'
down_revision = '2c9bd41c6a05'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('work_categories',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('archived', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_work_categories_workspace_id_workspaces')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_work_categories')),
    sa.UniqueConstraint('workspace_id', 'name', name=op.f('uq_work_categories_workspace_id_name'))
    )
    op.create_index(op.f('ix_work_categories_workspace_id'), 'work_categories', ['workspace_id'], unique=False)
    op.create_table('project_timelogging',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_project_timelogging_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('project_id', name=op.f('pk_project_timelogging'))
    )
    op.create_table('item_estimates',
    sa.Column('item_id', sa.Uuid(), nullable=False),
    sa.Column('original_estimate_seconds', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['work_items.id'], name=op.f('fk_item_estimates_item_id_work_items'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('item_id', name=op.f('pk_item_estimates'))
    )
    op.create_table('worklogs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('item_id', sa.Uuid(), nullable=False),
    sa.Column('author_id', sa.Uuid(), nullable=False),
    sa.Column('category_id', sa.Uuid(), nullable=True),
    sa.Column('worked_on', sa.Date(), nullable=False),
    sa.Column('time_spent_seconds', sa.Integer(), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], name=op.f('fk_worklogs_author_id_users')),
    sa.ForeignKeyConstraint(['category_id'], ['work_categories.id'], name=op.f('fk_worklogs_category_id_work_categories'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['item_id'], ['work_items.id'], name=op.f('fk_worklogs_item_id_work_items'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_worklogs'))
    )
    op.create_index(op.f('ix_worklogs_author_id'), 'worklogs', ['author_id'], unique=False)
    op.create_index(op.f('ix_worklogs_category_id'), 'worklogs', ['category_id'], unique=False)
    op.create_index(op.f('ix_worklogs_item_id'), 'worklogs', ['item_id'], unique=False)
    op.create_index(op.f('ix_worklogs_worked_on'), 'worklogs', ['worked_on'], unique=False)
    # ### end Alembic commands ###

    # --- data backfill for existing workspaces (spec 22) ---
    # New workspaces get these from the workspace.created hook / builtin-role seed;
    # existing ones are converged here. Values frozen in the migration on purpose.
    conn = op.get_bind()

    # 1. Seed default work categories for every existing workspace.
    default_categories = (
        "Development", "Investigation", "Code Review", "Meeting",
        "Discussion", "Documentation", "Testing",
    )
    workspace_ids = [row[0] for row in conn.execute(sa.text("SELECT id FROM workspaces"))]
    for workspace_id in workspace_ids:
        for position, name in enumerate(default_categories):
            conn.execute(
                sa.text(
                    "INSERT INTO work_categories "
                    "(id, workspace_id, name, position, archived, created_at, updated_at) "
                    "VALUES (gen_random_uuid(), :wid, :name, :pos, false, now(), now()) "
                    "ON CONFLICT (workspace_id, name) DO NOTHING"
                ),
                {"wid": workspace_id, "name": name, "pos": position},
            )

    # 2. Grant the new worklog.write permission to existing builtin admin/member roles
    #    (their stored permission sets predate this permission).
    conn.execute(
        sa.text(
            "UPDATE roles SET permissions = permissions || '[\"worklog.write\"]'::jsonb "
            "WHERE is_builtin AND key IN ('admin', 'member') "
            "AND NOT (permissions @> '[\"worklog.write\"]'::jsonb)"
        )
    )


def downgrade() -> None:
    # Drop the backfilled permission; the categories go with the dropped table.
    op.get_bind().execute(
        sa.text(
            "UPDATE roles SET permissions = permissions - 'worklog.write' "
            "WHERE is_builtin AND key IN ('admin', 'member')"
        )
    )
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_worklogs_worked_on'), table_name='worklogs')
    op.drop_index(op.f('ix_worklogs_item_id'), table_name='worklogs')
    op.drop_index(op.f('ix_worklogs_category_id'), table_name='worklogs')
    op.drop_index(op.f('ix_worklogs_author_id'), table_name='worklogs')
    op.drop_table('worklogs')
    op.drop_table('item_estimates')
    op.drop_table('project_timelogging')
    op.drop_index(op.f('ix_work_categories_workspace_id'), table_name='work_categories')
    op.drop_table('work_categories')
    # ### end Alembic commands ###
