"""items: reporter field (spec 30)

Revision ID: b82af9418040
Revises: cb60181ca656

"""
from alembic import op
import sqlalchemy as sa


revision = 'b82af9418040'
down_revision = 'cb60181ca656'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('work_items', sa.Column('reporter_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_work_items_reporter_id'), 'work_items', ['reporter_id'], unique=False)
    op.create_foreign_key(op.f('fk_work_items_reporter_id_users'), 'work_items', 'users', ['reporter_id'], ['id'])
    # Backfill: the event log knows who created every item — that actor is the
    # reporter for all pre-spec-30 items (guarded to actors that still exist).
    op.execute(
        """
        UPDATE work_items SET reporter_id = created.actor_id
        FROM (
            SELECT DISTINCT ON (entity_id) entity_id, actor_id
            FROM events
            WHERE event_type = 'item.created' AND entity_type = 'item'
            ORDER BY entity_id, id
        ) AS created
        WHERE work_items.id::text = created.entity_id
          AND created.actor_id IN (SELECT id FROM users)
        """
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_work_items_reporter_id_users'), 'work_items', type_='foreignkey')
    op.drop_index(op.f('ix_work_items_reporter_id'), table_name='work_items')
    op.drop_column('work_items', 'reporter_id')
    # ### end Alembic commands ###
