"""builtin field rules (spec 36)

Revision ID: b86859928b9f
Revises: 43c250fb2a01

"""
from alembic import op
import sqlalchemy as sa


revision = 'b86859928b9f'
down_revision = '43c250fb2a01'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('builtin_field_rules',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.Column('field', sa.String(length=30), nullable=False),
    sa.Column('subject_type', sa.String(length=10), nullable=False),
    sa.Column('subject_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_builtin_field_rules_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_builtin_field_rules')),
    sa.UniqueConstraint('workspace_id', 'project_id', 'field', 'subject_type', 'subject_id', name=op.f('uq_builtin_field_rules_workspace_id_project_id_field_subject_type_subject_id'))
    )
    op.create_index(op.f('ix_builtin_field_rules_project_id'), 'builtin_field_rules', ['project_id'], unique=False)
    op.create_index(op.f('ix_builtin_field_rules_workspace_id'), 'builtin_field_rules', ['workspace_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_builtin_field_rules_workspace_id'), table_name='builtin_field_rules')
    op.drop_index(op.f('ix_builtin_field_rules_project_id'), table_name='builtin_field_rules')
    op.drop_table('builtin_field_rules')
    # ### end Alembic commands ###
