"""Spec 117 — the Confluence importer's own tables.

Nine tables, all namespaced `confluence_*`, and nothing else. The autogenerated
draft also wanted to DROP `page_embeddings` and `item_embeddings` — spec 103
manages the embedding schema at runtime, deliberately outside `Base.metadata`, so
autogenerate cannot see why they exist — and `acme_notes`, the example plugin's
table, which is present only when that plugin is installed. Taking the generated
file as written would have deleted a live semantic index.

Revision ID: c117confluence
Revises: d117extid
"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision = "c117confluence"
down_revision = "d117extid"
branch_labels = None
depends_on = None

JSONB = postgresql.JSONB(astext_type=sa.Text())


def upgrade() -> None:
    op.create_table(
        "confluence_connections",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("base_url", sa.String(length=500), nullable=False),
        sa.Column("auth_mode", sa.String(length=20), nullable=False),
        sa.Column("username", sa.String(length=200), nullable=False),
        sa.Column("credential", sa.String(length=500), nullable=False),
        sa.Column("verify_ssl", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("is_default", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("source", sa.String(length=20), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_confluence_connections")),
        sa.UniqueConstraint("name", name=op.f("uq_confluence_connections_name")),
    )
    op.create_table(
        "confluence_snapshots",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("connection_id", sa.Uuid(), nullable=True),
        sa.Column("actor_id", sa.Uuid(), nullable=True),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("scope", JSONB, nullable=False),
        sa.Column("external_source", sa.String(length=200), nullable=False),
        sa.Column("base_url", sa.String(length=500), nullable=False),
        sa.Column(
            "include_history", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
        sa.Column("history_limit", sa.Integer(), nullable=True),
        sa.Column("include_attachments", sa.Boolean(), nullable=False),
        sa.Column("include_comments", sa.Boolean(), nullable=False),
        sa.Column("stage", sa.String(length=30), nullable=False),
        sa.Column("counts", JSONB, nullable=False),
        sa.Column("problems", JSONB, nullable=False),
        sa.Column("catalogs", JSONB, nullable=False),
        sa.Column("page_count", sa.Integer(), nullable=False),
        sa.Column("byte_size", sa.BigInteger(), nullable=False),
        sa.Column("started_at", sa.DateTime(), nullable=True),
        sa.Column("finished_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["actor_id"], ["users.id"],
            name=op.f("fk_confluence_snapshots_actor_id_users"), ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["connection_id"], ["confluence_connections.id"],
            name=op.f("fk_confluence_snapshots_connection_id_confluence_connections"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_confluence_snapshots")),
    )
    op.create_table(
        "confluence_plans",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("snapshot_id", sa.Uuid(), nullable=False),
        sa.Column("mappings", JSONB, nullable=False),
        sa.Column("options", JSONB, nullable=False),
        sa.Column("provisioned_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["snapshot_id"], ["confluence_snapshots.id"],
            name=op.f("fk_confluence_plans_snapshot_id_confluence_snapshots"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_confluence_plans")),
        sa.UniqueConstraint("name", name=op.f("uq_confluence_plans_name")),
    )
    op.create_table(
        "confluence_snapshot_pages",
        sa.Column("snapshot_id", sa.Uuid(), nullable=False),
        sa.Column("page_id", sa.String(length=64), nullable=False),
        sa.Column("space_key", sa.String(length=100), nullable=False),
        sa.Column("parent_id", sa.String(length=64), nullable=True),
        sa.Column("title", sa.String(length=500), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("payload", JSONB, nullable=False),
        sa.Column("versions", JSONB, nullable=False),
        sa.Column("restrictions", JSONB, nullable=False),
        sa.Column("labels", JSONB, nullable=False),
        sa.ForeignKeyConstraint(
            ["snapshot_id"], ["confluence_snapshots.id"],
            name=op.f("fk_confluence_snapshot_pages_snapshot_id_confluence_snapshots"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "snapshot_id", "page_id", name=op.f("pk_confluence_snapshot_pages")
        ),
    )
    op.create_index(
        "ix_confluence_snapshot_pages_parent",
        "confluence_snapshot_pages", ["snapshot_id", "parent_id"], unique=False,
    )
    op.create_index(
        "ix_confluence_snapshot_pages_snapshot",
        "confluence_snapshot_pages", ["snapshot_id", "page_id"], unique=False,
    )
    op.create_table(
        "confluence_snapshot_comments",
        sa.Column("snapshot_id", sa.Uuid(), nullable=False),
        sa.Column("comment_id", sa.String(length=64), nullable=False),
        sa.Column("page_id", sa.String(length=64), nullable=False),
        sa.Column("parent_comment_id", sa.String(length=64), nullable=True),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("author", sa.String(length=200), nullable=False),
        sa.Column("author_email", sa.String(length=320), nullable=False),
        sa.Column("created_at", sa.String(length=64), nullable=False),
        sa.Column("anchor", JSONB, nullable=True),
        sa.ForeignKeyConstraint(
            ["snapshot_id"], ["confluence_snapshots.id"],
            name=op.f("fk_confluence_snapshot_comments_snapshot_id_confluence_snapshots"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "snapshot_id", "comment_id", name=op.f("pk_confluence_snapshot_comments")
        ),
    )
    op.create_index(
        "ix_confluence_snapshot_comments_page",
        "confluence_snapshot_comments", ["snapshot_id", "page_id"], unique=False,
    )
    op.create_table(
        "confluence_snapshot_attachments",
        sa.Column("snapshot_id", sa.Uuid(), nullable=False),
        sa.Column("attachment_id", sa.String(length=64), nullable=False),
        sa.Column("page_id", sa.String(length=64), nullable=False),
        sa.Column("filename", sa.String(length=500), nullable=False),
        sa.Column("content_type", sa.String(length=200), nullable=False),
        sa.Column("size_bytes", sa.BigInteger(), nullable=False),
        sa.Column("storage_name", sa.String(length=500), nullable=False),
        sa.Column("storage_host_id", sa.Uuid(), nullable=True),
        sa.Column("download_path", sa.String(length=1000), nullable=False),
        sa.ForeignKeyConstraint(
            ["snapshot_id"], ["confluence_snapshots.id"],
            name=op.f("fk_confluence_snapshot_attachments_snapshot_id_confluence_snapshots"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "snapshot_id", "attachment_id", name=op.f("pk_confluence_snapshot_attachments")
        ),
    )
    op.create_index(
        "ix_confluence_snapshot_attachments_page",
        "confluence_snapshot_attachments", ["snapshot_id", "page_id"], unique=False,
    )
    op.create_table(
        "confluence_runs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("plan_id", sa.Uuid(), nullable=True),
        sa.Column("snapshot_id", sa.Uuid(), nullable=True),
        sa.Column("actor_id", sa.Uuid(), nullable=True),
        sa.Column("kind", sa.String(length=20), nullable=False),
        sa.Column("dry_run", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("plan_snapshot", JSONB, nullable=False),
        sa.Column("external_source", sa.String(length=200), nullable=False),
        sa.Column("stage", sa.String(length=30), nullable=False),
        sa.Column("counts", JSONB, nullable=False),
        sa.Column("problems", JSONB, nullable=False),
        sa.Column("report", JSONB, nullable=False),
        sa.Column("started_at", sa.DateTime(), nullable=True),
        sa.Column("finished_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["actor_id"], ["users.id"],
            name=op.f("fk_confluence_runs_actor_id_users"), ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["plan_id"], ["confluence_plans.id"],
            name=op.f("fk_confluence_runs_plan_id_confluence_plans"), ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["snapshot_id"], ["confluence_snapshots.id"],
            name=op.f("fk_confluence_runs_snapshot_id_confluence_snapshots"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_confluence_runs")),
    )
    op.create_table(
        "confluence_import_records",
        # BigInteger Identity, not a UUID: undo must be the exact inverse of write
        # order, and a monotonic integer is the only key that orders itself.
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("run_id", sa.Uuid(), nullable=False),
        sa.Column("entity_type", sa.String(length=40), nullable=False),
        sa.Column("entity_id", sa.String(length=64), nullable=False),
        sa.Column("action", sa.String(length=20), nullable=False),
        sa.Column("subject", sa.String(length=300), nullable=False),
        sa.Column("before", JSONB, nullable=True),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["run_id"], ["confluence_runs.id"],
            name=op.f("fk_confluence_import_records_run_id_confluence_runs"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_confluence_import_records")),
    )
    op.create_index(
        "ix_confluence_import_records_run",
        "confluence_import_records", ["run_id", "id"], unique=False,
    )
    op.create_table(
        "confluence_pending_refs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("run_id", sa.Uuid(), nullable=True),
        sa.Column("source_page_id", sa.Uuid(), nullable=False),
        sa.Column("external_source", sa.String(length=200), nullable=False),
        sa.Column("target_page_id", sa.String(length=64), nullable=False),
        sa.Column("target_title", sa.String(length=500), nullable=False),
        sa.Column("resolved", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.ForeignKeyConstraint(
            ["run_id"], ["confluence_runs.id"],
            name=op.f("fk_confluence_pending_refs_run_id_confluence_runs"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["source_page_id"], ["pages.id"],
            name=op.f("fk_confluence_pending_refs_source_page_id_pages"), ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_confluence_pending_refs")),
    )
    op.create_index(
        "ix_confluence_pending_refs_target",
        "confluence_pending_refs", ["target_page_id"], unique=False,
    )


def downgrade() -> None:
    for index, table in (
        ("ix_confluence_pending_refs_target", "confluence_pending_refs"),
        ("ix_confluence_import_records_run", "confluence_import_records"),
        ("ix_confluence_snapshot_attachments_page", "confluence_snapshot_attachments"),
        ("ix_confluence_snapshot_comments_page", "confluence_snapshot_comments"),
        ("ix_confluence_snapshot_pages_snapshot", "confluence_snapshot_pages"),
        ("ix_confluence_snapshot_pages_parent", "confluence_snapshot_pages"),
    ):
        op.drop_index(index, table_name=table)
    for table in (
        "confluence_pending_refs",
        "confluence_import_records",
        "confluence_runs",
        "confluence_snapshot_attachments",
        "confluence_snapshot_comments",
        "confluence_snapshot_pages",
        "confluence_plans",
        "confluence_snapshots",
        "confluence_connections",
    ):
        op.drop_table(table)
