"""item cycle records (spec 56)

Revision ID: c536f26534fb
Revises: 7ec22a4a1c25

"""
from alembic import op
import sqlalchemy as sa


revision = 'c536f26534fb'
down_revision = '7ec22a4a1c25'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('item_cycle_records',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('item_id', sa.Uuid(), nullable=False),
    sa.Column('cycle_id', sa.Uuid(), nullable=False),
    sa.Column('added_at', sa.DateTime(), nullable=False),
    sa.Column('removed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cycle_id'], ['cycles.id'], name=op.f('fk_item_cycle_records_cycle_id_cycles'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['item_id'], ['work_items.id'], name=op.f('fk_item_cycle_records_item_id_work_items'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_item_cycle_records'))
    )
    op.create_index(op.f('ix_item_cycle_records_cycle_id'), 'item_cycle_records', ['cycle_id'], unique=False)
    op.create_index(op.f('ix_item_cycle_records_item_id'), 'item_cycle_records', ['item_id'], unique=False)
    # Backfill: an OPEN stint for every current cycle assignment. added_at uses
    # the item's created_at (best available anchor — exact times only matter for
    # CLOSED stints, which scripts/backfill_cycle_history.py mines from events).
    op.execute(
        "INSERT INTO item_cycle_records (id, item_id, cycle_id, added_at) "
        "SELECT gen_random_uuid(), id, cycle_id, created_at FROM work_items "
        "WHERE cycle_id IS NOT NULL"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_item_cycle_records_item_id'), table_name='item_cycle_records')
    op.drop_index(op.f('ix_item_cycle_records_cycle_id'), table_name='item_cycle_records')
    op.drop_table('item_cycle_records')
    # ### end Alembic commands ###
