"""field visibility min read write roles

Revision ID: cb29f8c473c0
Revises: f91db80874a2

"""
from alembic import op
import sqlalchemy as sa


revision = 'cb29f8c473c0'
down_revision = 'f91db80874a2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # server_default backfills existing definitions with the ProjectRole defaults
    # (viewer-readable, member-writable) — the ORM sets values explicitly on insert.
    op.add_column(
        'field_definitions',
        sa.Column('min_read_role', sa.String(length=20), nullable=False, server_default='viewer'),
    )
    op.add_column(
        'field_definitions',
        sa.Column('min_write_role', sa.String(length=20), nullable=False, server_default='member'),
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('field_definitions', 'min_write_role')
    op.drop_column('field_definitions', 'min_read_role')
    # ### end Alembic commands ###
