"""RADD-1032 + RADD-1033: mail intake hardening columns.

Two independent issues, one migration (one worker adds one migration; the
supervisor merges the sibling heads).

**RADD-1032** — `mail_sources.trusted_authserv_id`. The `Authentication-Results`
authserv-id whose SPF/DKIM/DMARC verdict a source trusts — its own MX's stamp.
NULL is the default and reproduces today's behaviour exactly: `From:` is taken at
face value. Set it, and a message failing (or lacking) that verdict is recorded
as received but attributed to SYSTEM, never to the account it may have forged.

**RADD-1033** — the raw inbound bytes, retained per `MAIL_RAW_RETENTION_DAYS`
through the spec-102 blob seam and keyed off the `mail_messages` row. Three
columns because that is a `BlobRef`: the opaque storage name, the host it lives
on (`ON DELETE SET NULL` — losing the host must not delete the thread history),
and the size. INBOUND rows only; NULL when retention is off, when there was no
Message-ID to key a row off, or when no storage host is configured.

Written by hand rather than autogenerated, so it carries only these columns and
none of the known false positives a full autogenerate drags in (the
runtime-managed pgvector tables, the example plugin, the raw-SQL partial indexes,
the surviving `doc_`→`page_` names, `ix_mail_sources_default_project`).

Revision ID: d1044mailhard
Revises: d1043slatype
"""

import sqlalchemy as sa
from alembic import op

revision = "d1044mailhard"
down_revision = "d1043slatype"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # RADD-1032
    op.add_column(
        "mail_sources", sa.Column("trusted_authserv_id", sa.String(length=255), nullable=True)
    )
    # RADD-1033
    op.add_column(
        "mail_messages", sa.Column("raw_storage_name", sa.String(length=255), nullable=True)
    )
    op.add_column("mail_messages", sa.Column("raw_host_id", sa.Uuid(), nullable=True))
    op.add_column("mail_messages", sa.Column("raw_size_bytes", sa.Integer(), nullable=True))
    op.create_foreign_key(
        op.f("fk_mail_messages_raw_host_id_storage_hosts"),
        "mail_messages",
        "storage_hosts",
        ["raw_host_id"],
        ["id"],
        ondelete="SET NULL",
    )


def downgrade() -> None:
    op.drop_constraint(
        op.f("fk_mail_messages_raw_host_id_storage_hosts"), "mail_messages", type_="foreignkey"
    )
    op.drop_column("mail_messages", "raw_size_bytes")
    op.drop_column("mail_messages", "raw_host_id")
    op.drop_column("mail_messages", "raw_storage_name")
    op.drop_column("mail_sources", "trusted_authserv_id")
