"""spec 111: forgejo connections and repositories as rows

Hand-written, not autogenerated as emitted. Autogenerate wanted to drop the
embeddings tables (spec 103 manages them at RUNTIME, deliberately outside
`Base.metadata`), the acme-notes example plugin's table, and three expression
indexes it cannot round-trip. Only the two new tables belong here.

Revision ID: d111fjconn
Revises: d110ssoprov
Create Date: 2026-08-02
"""

import sqlalchemy as sa
from alembic import op

revision = "d111fjconn"
down_revision = "d110ssoprov"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.create_table(
        "forgejo_connections",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("base_url", sa.String(length=500), nullable=False),
        sa.Column("api_token", sa.String(length=500), nullable=False),
        sa.Column("webhook_secret", sa.String(length=200), nullable=False),
        sa.Column("active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("verify_ssl", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_forgejo_connections")),
        sa.UniqueConstraint("name", name=op.f("uq_forgejo_connections_name")),
    )
    op.create_table(
        "forgejo_repos",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("connection_id", sa.Uuid(), nullable=False),
        sa.Column("full_name", sa.String(length=300), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=True),
        sa.Column("default_branch", sa.String(length=200), nullable=False),
        sa.Column("last_backfill_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["connection_id"],
            ["forgejo_connections.id"],
            name=op.f("fk_forgejo_repos_connection_id_forgejo_connections"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_forgejo_repos_project_id_projects"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_forgejo_repos")),
        sa.UniqueConstraint(
            "connection_id", "full_name", name=op.f("uq_forgejo_repos_connection_id_full_name")
        ),
    )
    op.create_index(
        op.f("ix_forgejo_repos_connection_id"), "forgejo_repos", ["connection_id"], unique=False
    )
    op.create_index(
        op.f("ix_forgejo_repos_project_id"), "forgejo_repos", ["project_id"], unique=False
    )


def downgrade() -> None:
    op.drop_index(op.f("ix_forgejo_repos_project_id"), table_name="forgejo_repos")
    op.drop_index(op.f("ix_forgejo_repos_connection_id"), table_name="forgejo_repos")
    op.drop_table("forgejo_repos")
    op.drop_table("forgejo_connections")
