"""notify email retry backoff (RADD-997)

Two columns on `notifications` so a failed send costs the row its place in the
queue instead of being reconsidered by the next five-second tick:

* `email_attempts` — consecutive delivery failures, 0 for every existing row
  (none of which is mid-failure: the state did not exist);
* `email_next_try` — the earliest tick allowed to look at the row again. NULL
  means now, which is why the backfill is nothing at all: every row already in
  the table is immediately eligible, exactly as it is today.

Both loops add `(email_next_try IS NULL OR email_next_try <= now())` to their
selection, so the columns are inert until something fails. The ladder itself is
`notify/retry.py` — policy, not schema.

The autogenerated diff also carried a dozen index/constraint RENAMES left over
from the docs→pages rename and several partial indexes alembic cannot see the
predicate of; all of them are false positives against a schema already at head,
and all are stripped. What remains is the two ADD COLUMNs.

Revision ID: d997mailretry
Revises: d979mailbind
Create Date: 2026-08-08
"""
import sqlalchemy as sa
from alembic import op

revision = 'd997mailretry'
down_revision = 'd980contacts'
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.add_column(
        'notifications',
        sa.Column('email_attempts', sa.Integer(), server_default='0', nullable=False),
    )
    op.add_column('notifications', sa.Column('email_next_try', sa.DateTime(), nullable=True))


def downgrade() -> None:
    op.drop_column('notifications', 'email_next_try')
    op.drop_column('notifications', 'email_attempts')
