"""cycles releases item planning fields and links

Revision ID: e4390d7d9542
Revises: 6afdeaf4f62d

"""
from alembic import op
import sqlalchemy as sa


revision = 'e4390d7d9542'
down_revision = '6afdeaf4f62d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cycles',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('goal', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_cycles_workspace_id_workspaces')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cycles'))
    )
    op.create_index(op.f('ix_cycles_workspace_id'), 'cycles', ['workspace_id'], unique=False)
    op.create_table('releases',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('version', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('released_at', sa.DateTime(), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_releases_project_id_projects')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_releases')),
    sa.UniqueConstraint('project_id', 'version', name=op.f('uq_releases_project_id_version'))
    )
    op.create_index(op.f('ix_releases_project_id'), 'releases', ['project_id'], unique=False)
    op.create_table('item_links',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('source_item_id', sa.Uuid(), nullable=False),
    sa.Column('target_item_id', sa.Uuid(), nullable=False),
    sa.Column('link_type', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['source_item_id'], ['work_items.id'], name=op.f('fk_item_links_source_item_id_work_items'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_item_id'], ['work_items.id'], name=op.f('fk_item_links_target_item_id_work_items'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_item_links')),
    sa.UniqueConstraint('source_item_id', 'target_item_id', 'link_type', name=op.f('uq_item_links_source_item_id_target_item_id_link_type'))
    )
    op.create_index(op.f('ix_item_links_source_item_id'), 'item_links', ['source_item_id'], unique=False)
    op.create_index(op.f('ix_item_links_target_item_id'), 'item_links', ['target_item_id'], unique=False)
    op.add_column('work_items', sa.Column('start_date', sa.Date(), nullable=True))
    op.add_column('work_items', sa.Column('target_date', sa.Date(), nullable=True))
    op.add_column('work_items', sa.Column('cycle_id', sa.Uuid(), nullable=True))
    op.add_column('work_items', sa.Column('release_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_work_items_cycle_id'), 'work_items', ['cycle_id'], unique=False)
    op.create_index(op.f('ix_work_items_release_id'), 'work_items', ['release_id'], unique=False)
    op.create_foreign_key(op.f('fk_work_items_release_id_releases'), 'work_items', 'releases', ['release_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('fk_work_items_cycle_id_cycles'), 'work_items', 'cycles', ['cycle_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_work_items_cycle_id_cycles'), 'work_items', type_='foreignkey')
    op.drop_constraint(op.f('fk_work_items_release_id_releases'), 'work_items', type_='foreignkey')
    op.drop_index(op.f('ix_work_items_release_id'), table_name='work_items')
    op.drop_index(op.f('ix_work_items_cycle_id'), table_name='work_items')
    op.drop_column('work_items', 'release_id')
    op.drop_column('work_items', 'cycle_id')
    op.drop_column('work_items', 'target_date')
    op.drop_column('work_items', 'start_date')
    op.drop_index(op.f('ix_item_links_target_item_id'), table_name='item_links')
    op.drop_index(op.f('ix_item_links_source_item_id'), table_name='item_links')
    op.drop_table('item_links')
    op.drop_index(op.f('ix_releases_project_id'), table_name='releases')
    op.drop_table('releases')
    op.drop_index(op.f('ix_cycles_workspace_id'), table_name='cycles')
    op.drop_table('cycles')
    # ### end Alembic commands ###
