"""installed_plugins (spec 93 A4 plugin manager)

Revision ID: e53d08a57e29
Revises: a29615cf474d

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = 'e53d08a57e29'
down_revision = 'a29615cf474d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('installed_plugins',
    sa.Column('id', sa.String(length=200), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('state', sa.String(length=20), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_installed_plugins'))
    )
    # NOTE: autogenerate also proposed dropping the milestones table + ix_doc_pages_fts
    # — false positives (milestones is an installable-only plugin not in the default
    # metadata scan; the FTS index is a GIN expression index). Removed: this migration
    # only adds installed_plugins.


def downgrade() -> None:
    op.drop_table('installed_plugins')
