"""approvals (spec 71)

Revision ID: ea8e44297500
Revises: d8402cfe3773

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = 'ea8e44297500'
down_revision = 'd8402cfe3773'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('approval_requests',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('item_id', sa.Uuid(), nullable=False),
    sa.Column('transition_id', sa.Uuid(), nullable=True),
    sa.Column('approver_user_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('approver_team_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('required', sa.Integer(), nullable=False),
    sa.Column('to_state_id', sa.Uuid(), nullable=False),
    sa.Column('requested_by', sa.Uuid(), nullable=True),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['work_items.id'], name=op.f('fk_approval_requests_item_id_work_items'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['requested_by'], ['users.id'], name=op.f('fk_approval_requests_requested_by_users')),
    sa.ForeignKeyConstraint(['to_state_id'], ['states.id'], name=op.f('fk_approval_requests_to_state_id_states')),
    sa.ForeignKeyConstraint(['transition_id'], ['workflow_transitions.id'], name=op.f('fk_approval_requests_transition_id_workflow_transitions'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_approval_requests'))
    )
    op.create_index(op.f('ix_approval_requests_item_id'), 'approval_requests', ['item_id'], unique=False)
    op.create_index(op.f('ix_approval_requests_status'), 'approval_requests', ['status'], unique=False)
    op.create_table('approval_votes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('request_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('verdict', sa.String(length=10), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['request_id'], ['approval_requests.id'], name=op.f('fk_approval_votes_request_id_approval_requests'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_approval_votes_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_approval_votes')),
    sa.UniqueConstraint('request_id', 'user_id', name=op.f('uq_approval_votes_request_id_user_id'))
    )
    op.create_index(op.f('ix_approval_votes_request_id'), 'approval_votes', ['request_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_approval_votes_request_id'), table_name='approval_votes')
    op.drop_table('approval_votes')
    op.drop_index(op.f('ix_approval_requests_status'), table_name='approval_requests')
    op.drop_index(op.f('ix_approval_requests_item_id'), table_name='approval_requests')
    op.drop_table('approval_requests')
    # ### end Alembic commands ###
