"""user profile: avatar + timezone (spec 34)

Revision ID: ec39cc8b4bb3
Revises: 2af6a5125285

"""
from alembic import op
import sqlalchemy as sa


revision = 'ec39cc8b4bb3'
down_revision = '2af6a5125285'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar_color', sa.String(length=7), nullable=True))
    op.add_column('users', sa.Column('avatar_emoji', sa.String(length=16), nullable=True))
    op.add_column('users', sa.Column('timezone', sa.String(length=64), server_default='', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'timezone')
    op.drop_column('users', 'avatar_emoji')
    op.drop_column('users', 'avatar_color')
    # ### end Alembic commands ###
