"""sla work_week_only (spec 35)

Revision ID: ed44871272ba
Revises: ec39cc8b4bb3

"""
from alembic import op
import sqlalchemy as sa


revision = 'ed44871272ba'
down_revision = 'ec39cc8b4bb3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sla_policies', sa.Column('work_week_only', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sla_policies', 'work_week_only')
    # ### end Alembic commands ###
