"""spec 92 adopters: migrate dashboard_shares to access_grants

Dashboards were the one RBAC-controlled resource that never adopted the generic
access framework: `dashboard_shares` was a verbatim copy of `view_shares`, which
spec 92 itself deleted. This moves the rows into `access_grants` under
resource_type 'dashboard' and drops the bespoke table, mirroring
925809931622 (the views migration) exactly.

HAND-WRITTEN, not autogenerated. Autogenerate produced three wrong things here:
it dropped `dashboard_shares` with no data copy (silent loss of every share);
it dropped `acme_notes`, which belongs to the out-of-tree example plugin and is
invisible to env.py's metadata; and it dropped `ix_doc_pages_fts`, a functional
GIN index it cannot round-trip. Only the dashboard ops below are intended.

Revision ID: ef4be162afa1
Revises: f1a2b3c4d5e6

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = 'ef4be162afa1'
down_revision = 'f1a2b3c4d5e6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # Copy BEFORE dropping: resource_type='dashboard', resource_id = the
    # dashboard id, subject user/team, access = the ShareLevel. project_id stays
    # NULL — dashboards are global, not project-scoped.
    op.execute(
        """
        INSERT INTO access_grants (id, resource_type, resource_id, subject_type, subject_id, access, project_id)
        SELECT gen_random_uuid(), 'dashboard', dashboard_id::text,
               CASE WHEN user_id IS NOT NULL THEN 'user' ELSE 'team' END,
               COALESCE(user_id, team_id), level, NULL
        FROM dashboard_shares
        """
    )
    op.drop_index(op.f('ix_dashboard_shares_dashboard_id'), table_name='dashboard_shares')
    op.drop_index(op.f('ix_dashboard_shares_team_id'), table_name='dashboard_shares')
    op.drop_index(op.f('ix_dashboard_shares_user_id'), table_name='dashboard_shares')
    op.drop_table('dashboard_shares')


def downgrade() -> None:
    op.create_table('dashboard_shares',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('dashboard_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('team_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('level', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.CheckConstraint('(user_id IS NULL) <> (team_id IS NULL)', name=op.f('ck_dashboard_shares_one_subject')),
    sa.ForeignKeyConstraint(['dashboard_id'], ['dashboards.id'], name=op.f('fk_dashboard_shares_dashboard_id_dashboards'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], name=op.f('fk_dashboard_shares_team_id_teams'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_dashboard_shares_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_dashboard_shares')),
    sa.UniqueConstraint('dashboard_id', 'team_id', name=op.f('uq_dashboard_shares_dashboard_id_team_id')),
    sa.UniqueConstraint('dashboard_id', 'user_id', name=op.f('uq_dashboard_shares_dashboard_id_user_id'))
    )
    op.create_index(op.f('ix_dashboard_shares_user_id'), 'dashboard_shares', ['user_id'], unique=False)
    op.create_index(op.f('ix_dashboard_shares_team_id'), 'dashboard_shares', ['team_id'], unique=False)
    op.create_index(op.f('ix_dashboard_shares_dashboard_id'), 'dashboard_shares', ['dashboard_id'], unique=False)
    # Move the grants back, then remove them from the generic table.
    op.execute(
        """
        INSERT INTO dashboard_shares (id, dashboard_id, user_id, team_id, level)
        SELECT gen_random_uuid(), resource_id::uuid,
               CASE WHEN subject_type = 'user' THEN subject_id END,
               CASE WHEN subject_type = 'team' THEN subject_id END,
               access
        FROM access_grants WHERE resource_type = 'dashboard'
        """
    )
    op.execute("DELETE FROM access_grants WHERE resource_type = 'dashboard'")
