"""audit: event diffs + indexes, weblinks, vcs links

Revision ID: f0f365b7e495
Revises: f2b9d5e83a10

"""
from alembic import op
import sqlalchemy as sa


revision = 'f0f365b7e495'
down_revision = 'f2b9d5e83a10'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('item_vcs_links',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('item_id', sa.Uuid(), nullable=False),
    sa.Column('ref_type', sa.String(length=20), nullable=False),
    sa.Column('provider', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('url', sa.String(length=2000), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('external_id', sa.String(length=200), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['work_items.id'], name=op.f('fk_item_vcs_links_item_id_work_items'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_item_vcs_links'))
    )
    op.create_index(op.f('ix_item_vcs_links_item_id'), 'item_vcs_links', ['item_id'], unique=False)
    op.create_table('item_web_links',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('item_id', sa.Uuid(), nullable=False),
    sa.Column('url', sa.String(length=2000), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('category', sa.String(length=20), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['work_items.id'], name=op.f('fk_item_web_links_item_id_work_items'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_item_web_links'))
    )
    op.create_index(op.f('ix_item_web_links_item_id'), 'item_web_links', ['item_id'], unique=False)
    op.create_index('ix_events_actor_id', 'events', ['actor_id'], unique=False)
    op.create_index('ix_events_entity', 'events', ['entity_type', 'entity_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_events_entity', table_name='events')
    op.drop_index('ix_events_actor_id', table_name='events')
    op.drop_index(op.f('ix_item_web_links_item_id'), table_name='item_web_links')
    op.drop_table('item_web_links')
    op.drop_index(op.f('ix_item_vcs_links_item_id'), table_name='item_vcs_links')
    op.drop_table('item_vcs_links')
    # ### end Alembic commands ###
