"""item key aliases (spec 68)

Revision ID: f7392cb631ca
Revises: c4f8a25d91e7

"""
from alembic import op
import sqlalchemy as sa


revision = 'f7392cb631ca'
down_revision = 'c4f8a25d91e7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('item_key_aliases',
    sa.Column('old_key', sa.String(length=60), nullable=False),
    sa.Column('item_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['work_items.id'], name=op.f('fk_item_key_aliases_item_id_work_items'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('old_key', name=op.f('pk_item_key_aliases'))
    )
    op.create_index(op.f('ix_item_key_aliases_item_id'), 'item_key_aliases', ['item_id'], unique=False)
    # (autogenerate also proposed dropping ix_doc_pages_fts — a migration-built
    # expression index the models don't declare; removed, do not drop it.)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_item_key_aliases_item_id'), table_name='item_key_aliases')
    op.drop_table('item_key_aliases')
    # ### end Alembic commands ###
