"""items kind parent assignee team; comments

Revision ID: f91db80874a2
Revises: bce2ec0d416a

"""
from alembic import op
import sqlalchemy as sa


revision = 'f91db80874a2'
down_revision = 'bce2ec0d416a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('item_id', sa.Uuid(), nullable=False),
    sa.Column('author_id', sa.Uuid(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], name=op.f('fk_comments_author_id_users')),
    sa.ForeignKeyConstraint(['item_id'], ['work_items.id'], name=op.f('fk_comments_item_id_work_items'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_comments'))
    )
    op.create_index(op.f('ix_comments_author_id'), 'comments', ['author_id'], unique=False)
    op.create_index(op.f('ix_comments_item_id'), 'comments', ['item_id'], unique=False)
    # server_default backfills pre-hierarchy rows as ItemKind.ISSUE and stays as the DB default.
    op.add_column('work_items', sa.Column('kind', sa.String(length=20), nullable=False, server_default='issue'))
    op.add_column('work_items', sa.Column('parent_id', sa.Uuid(), nullable=True))
    op.add_column('work_items', sa.Column('assignee_id', sa.Uuid(), nullable=True))
    op.add_column('work_items', sa.Column('team_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_work_items_assignee_id'), 'work_items', ['assignee_id'], unique=False)
    op.create_index(op.f('ix_work_items_parent_id'), 'work_items', ['parent_id'], unique=False)
    op.create_index(op.f('ix_work_items_team_id'), 'work_items', ['team_id'], unique=False)
    op.create_foreign_key(op.f('fk_work_items_assignee_id_users'), 'work_items', 'users', ['assignee_id'], ['id'])
    op.create_foreign_key(op.f('fk_work_items_team_id_teams'), 'work_items', 'teams', ['team_id'], ['id'])
    op.create_foreign_key(op.f('fk_work_items_parent_id_work_items'), 'work_items', 'work_items', ['parent_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_work_items_parent_id_work_items'), 'work_items', type_='foreignkey')
    op.drop_constraint(op.f('fk_work_items_team_id_teams'), 'work_items', type_='foreignkey')
    op.drop_constraint(op.f('fk_work_items_assignee_id_users'), 'work_items', type_='foreignkey')
    op.drop_index(op.f('ix_work_items_team_id'), table_name='work_items')
    op.drop_index(op.f('ix_work_items_parent_id'), table_name='work_items')
    op.drop_index(op.f('ix_work_items_assignee_id'), table_name='work_items')
    op.drop_column('work_items', 'team_id')
    op.drop_column('work_items', 'assignee_id')
    op.drop_column('work_items', 'parent_id')
    op.drop_column('work_items', 'kind')
    op.drop_index(op.f('ix_comments_item_id'), table_name='comments')
    op.drop_index(op.f('ix_comments_author_id'), table_name='comments')
    op.drop_table('comments')
    # ### end Alembic commands ###
