"""scoped settings table spec 50

Revision ID: faadd4470e3e
Revises: 41196e02047c

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = 'faadd4470e3e'
down_revision = '41196e02047c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scoped_settings',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('scope', sa.String(length=20), nullable=False),
    sa.Column('scope_id', sa.Uuid(), nullable=True),
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('value', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_scoped_settings')),
    sa.UniqueConstraint('scope', 'scope_id', 'key', name=op.f('uq_scoped_settings_scope_scope_id_key'))
    )
    op.create_index(op.f('ix_scoped_settings_key'), 'scoped_settings', ['key'], unique=False)
    op.create_index(op.f('ix_scoped_settings_scope'), 'scoped_settings', ['scope'], unique=False)
    op.create_index(op.f('ix_scoped_settings_scope_id'), 'scoped_settings', ['scope_id'], unique=False)
    # NOTE: the autogenerate also proposed dropping ix_doc_pages_fts — a false
    # positive (Alembic can't introspect the functional GIN expression index).
    # Deliberately omitted so the docs FTS index is preserved.
    # ### end Alembic commands ###


def downgrade() -> None:
    op.drop_index(op.f('ix_scoped_settings_scope_id'), table_name='scoped_settings')
    op.drop_index(op.f('ix_scoped_settings_scope'), table_name='scoped_settings')
    op.drop_index(op.f('ix_scoped_settings_key'), table_name='scoped_settings')
    op.drop_table('scoped_settings')
    # ### end Alembic commands ###
